region: ap-south-1
cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    stack:
      auto: false
spring:
  application:
    name: aws-s3
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error

server:
  port: 8081

# This is used to publish the message
sqs:
  url: https://sqs.ap-south-1.amazonaws.com/568121766349/testsqskalandhar