aws:
  access_key: ${AWS_ACCESS_KEY}
  secret_key: ${AWS_SECRET_KEY}
  region: ${REGION_SOUTH}

  aws:
    region:
      static: ap-south-1
      auto: false
    stack:
      auto: false

spring:
  application:
    name: aws-s3
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error

server:
  port: 8083