aws:
  access_key: ${AWS_ACCESS_KEY}
  secret_key: ${AWS_SECRET_KEY}
  region: ${REGION_SOUTH}
spring:
  application:
    name: aws-cloudwatch

server:
  port: 8084

# This is used to publish the message
log:
  group:
    name: mu-user-crud-app
  stream:
    name: my-user-crud-app-log-stream